#! /bin/sh
#монитор
xrandr --output DP-0 --mode 1920x1080 --rate 143
xrandr --output HDMI-0 --mode 2560x1440 --rate 74 --right-of DP-0
#
#мышка
xinput --set-prop 9 'libinput Accel Speed' -0.8 
pgrep -x sxhkd > /dev/null || sxhkd &

# fix some Java applications
# wmname LG3D

# workspaces
bspc monitor DP-0 -d 1 2 3 4 
bspc monitor HDMI-0 -d 5 6 7 8
#bspc monitor LVDS-1 -d 7  # TODO: multiple monitors

bspc config focus_follows_pointer true

# Window borders (Auto-Generate)
bspc config focused_border_color "#7A1FE2"
bspc config normal_border_color "#717276"
bspc config border_width 3
bspc config borderless_monocle true

bspc config active_border_color "#B23DFF"
bspc config presel_feedback_color "#C12D9A"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 10

# moving floating windows and resize them with mouse, hold mod key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating
bspc rule -a steam desktop='3' 

# start resources
xrdb merge ~/.Xresources

# python script to always initialize with a different wallpaper:
# TODO: Add loading of basic scripts
~/.config/bspwm/scripts/launch.sh &
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
#pkill battery-alert; ~/bin/battery-alert &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/4.conf &

# autostart
flameshot &
diodon &
